---
on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  MSVC:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build
        run: nmake /nologo
      - name: Test
        run: python3 tester.py
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install cppcheck
        run: sudo apt-get install -y cppcheck
      - name: Run cppcheck
        run: cppcheck --enable=all *.cpp
